### ISSUE TITLE
feat: Package as a mobile application using capacitor

### ISSUE THREAD

**Issue by kubo6472** [Explicit12/utube#1]
Ref. https://capacitorjs.com/docs/getting-started

**Comment by Explicit12** [comment]
Hi! Thanks for suggestion. I have no plans about mobile version for now. The app was designed exactly as wen app. I want to fix existing bugs and finish basic functional for now.

**Comment by Explicit12** [comment]
Hi! I've planned app as web application, and I'm developing this idea for now. Thanks for your suggestion, I'll consider it, but not in the nearest future. I would like to suggest you to try [VueTube](https://github.com/VueTubeApp/VueTube) as an alternative.
